apiVersion: apps/v1
kind: Deployment
metadata:
  name: Springboot-deployment
  labels:
    app: Springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Springboot
  template:
    metadata:
      labels:
        app: Springboot
    spec:
      containers:
      - name: Springboot
        image: koushik0802/springboot:org.jenkinsci.plugins.workflow.cps.EnvActionImpl@676c49d6:BUILD_NUMBER
        ports:
        - containerPort: 8081
